eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://master:8711/eureka/
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: oauth
    lease-renewal-interval-in-seconds: 5 #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
spring:
  datasource:
    druid:
      enable: true
      url: jdbc:mysql://182.61.49.195:3306/travel_user?allowMultiQueries=true&useSSL=false
      username: root
      password: 29147605/*-+@tcf
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    database: 0
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            client-id: oauth-client-id
            client-secret: oauth-client-secret
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
